"""Add AuditLog model

Revision ID: 499b6d42f2d6
Revises: 976d7265329b
Create Date: 2025-09-04 08:46:56.922946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '499b6d42f2d6'
down_revision = '976d7265329b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
