"""Add event type importance recurrence

Revision ID: 56a003d78b0a
Revises: 64b2ae3ca293
Create Date: 2025-09-03 13:43:54.452655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a003d78b0a'
down_revision = '64b2ae3ca293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_type'))
        batch_op.drop_column('recurrence')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('is_important')
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
