"""Add event color and reminder fields

Revision ID: 64b2ae3ca293
Revises: 3b53d8542118
Create Date: 2025-09-03 11:29:01.538506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b2ae3ca293'
down_revision = '3b53d8542118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('reminder')
        batch_op.drop_column('all_day')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
